apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-elasticsearch-master-1
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: elasticsearch-master-elasticsearch-master-1
    namespace: kibana
  nfs:
    path: "/lv-data/elk/"
    server: "192.168.1.30"
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-client
  volumeMode: Filesystem