# metallb-config.yaml
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ips-pool
  namespace: metallb-system
spec:
  addresses:
  - 10.88.0.240-10.88.0.250
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: network-l2
  namespace: metallb-system
spec:
  ipAddressPools:
  - ips-pool

