apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
{{/*  name: {{ include "nginx.fullname" . }}*/}}
  labels:
    tier: backend
{{/*    {{- include "nginx.labels" . | nindent 4 }}*/}}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
{{/*      {{- include "nginx.selectorLabels" . | nindent 6 }}*/}}
      app: nginx
      tier: backend
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: nginx
        tier: backend
{{/*        {{- include "nginx.selectorLabels" . | nindent 8 }}*/}}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "nginx.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
            claimName: task-pv-claim
        - name: nginx-config
          configMap:
            name: my-config
        - name: confi-d
          configMap:
            name: configd
{{/*        - name: tz*/}}
{{/*          configMap:*/}}
{{/*            name: tz*/}}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: TZ
              value: Asia/Ho_Chi_Minh
          volumeMounts:
            {{ range $path, $bytes := .Files.Glob ( printf "files/**") }}
            {{ $name := base $path }}
            - name: nginx-config
              mountPath: {{ print "/etc/nginx/" (index (regexSplit "files" (dir $path) -1) 1) $name | indent 2 }}
              subPath: {{- sha256sum (printf "%s" (index (regexSplit "files" (dir $path) -1) 1 ) $name ) | indent 2 }}
            {{ end }}

            - name: confi-d
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
{{/*            - name: tz*/}}
{{/*              mountPath: /etc/localtime*/}}

            - name: task-pv-storage
              mountPath: "/code"

          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
