apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx.fullname" . }}
  labels:
    app: nginx
    tier: backend
{{/*    {{- include "nginx.labels" . | nindent 4 }}*/}}

spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: nginx
    tier: backend
{{/*    {{- include "nginx.selectorLabels" . | nindent 4 }}*/}}

