apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana-logging
  namespace: default
  labels:
    k8s-app: kibana-logging
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: kibana-logging
  template:
    metadata:
      labels:
        k8s-app: kibana-logging
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: 'docker/default'
    spec:
      containers:
      - name: kibana-logging
        image: ccr.ccs.tencentyun.com/lvvimage/kibana:7.4.2
        imagePullPolicy: IfNotPresent
        # resources:
        #   # need more cpu upon initialization, therefore burstable class
        #   limits:
        #     cpu: 1000m
        #     memory: 2024Mi
        #   requests:
        #     cpu: 100m
        #     memory: 1024Mi
        env:
        - name: TZ
          value: Asia/Ho_Chi_Minh
        ports:
        - containerPort: 5601
          name: ui
          protocol: TCP
        volumeMounts:
        - name: config-volume
          mountPath: /usr/share/kibana/config
      volumes:
      - name: config-volume
        configMap:
          name: kibana-configmap-7.4.2
          items:
            - key: "kibana.yml"
              path: "kibana.yml"