apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  restartPolicy: Never
  containers:
    - name: ta-c
      image: "centos:7"
      command: ["/bin/bash","-c", "sleep 100000"]

# kubectl exec test -c ta-c -i --tty -- /bin/bash