apiVersion: v1
kind: Service
metadata:
  name: {{ include "php-fpm.fullname" . }}
  labels:
    app: php
{{/*        {{- include "php-fpm.labels" . | nindent 4 }}*/}}
    tier: backend

spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP

  selector:
{{/*        {{- include "php-fpm.selectorLabels" . | nindent 4 }}*/}}
    app: php
    tier: backend
